name: InterDC
version: '${version}'
description: Discord in Minecraft with interactive screens, live sync, visual presets, health diagnostics and Bedrock-ready support.
main: com.interdc.InterDCPlugin
api-version: '1.21'
author: InterDC

# Optional plugin integrations
softdepend:
  - floodgate
  - Geyser-Spigot

commands:
  interdc:
    description: Main InterDC command
    usage: /interdc (or /dc) <create|link|link2|style|perf|health|lockchannel|webhook|remove|reload|move|lang>
    aliases:
      - dc

permissions:
  interdc.admin:
    description: Allows managing InterDC screens
    default: op
